### ISSUE TITLE
Auth0JWTToken doesn't seem to load app metadata when using bearer token.

### ISSUE THREAD

**Issue by geekbeast** [auth0/auth0-spring-security-api#14]
Realized that (1) java servlet headers are case insensitive and (2) that it was failing at a different point so re-purposing issue. 

I've gotten everything working except that roles aren't being received server side when just using a bearer token as described in the docs. This seems to make sense at the data is loaded by the JWTVerifier.verify(...) method and only includes bearer token fields.

Given that it does attempt to populate roles, there must be someway of requesting a token with the app metadata encoded that's not covered in the docs here: https://auth0.com/docs/quickstart/backend/java-spring-security/01-authentication

**Comment by geekbeast** [comment]
Also just realized we were using older version of the libraries. After upgrade to latest, still seeing issue above.

I think this is mostly a doc issue-- it's not clear how to construct the request to include app metadata in the bearer token, which is what the code seems to expect. We were able to work around it by using the authentication java client to retrieve the data and update the granted authorities.

**Comment by arcseldon** [comment]
@geekbeast - Please refer to our [Sample for this library](https://github.com/auth0-samples/auth0-spring-security-api-sample#add-role-based-authorization-by-creating-an-auth0-rule) - the README goes into some detail how to setup a RULE in the Auth0 Dashboard that would for example add ROLES to a JWT Token.

Furthermore, you can use the [AuthorityStrategy](https://github.com/auth0/auth0-spring-security-api#default-configuration) configuration property to select what the API expects to read - indicates whether authorization claims against the Principal shall be GROUPS, ROLES or SCOPE based. Default is ROLES.  

Please let me know if anything still unclear, be happy to assist.

**Comment by arcseldon** [comment]
@geekbeast - Re. latest libraries - the dependencies were updated 2 days ago too :)

**Comment by geekbeast** [comment]
Thanks! We already have all that setup. 

The issue is that that roles aren't showing up with the standard way of loading the bearer token in the API.

Here's what we ended up doing:

```java
@Override
    public Authentication authenticate( Authentication authentication ) throws AuthenticationException {
        super.authenticate( authentication );
        final Auth0JWTToken tokenAuth = ( (Auth0JWTToken) authentication );
        UserProfile profile = auth0Client.tokenInfo( tokenAuth.getJwt() ).execute();
        @SuppressWarnings( "unchecked" )
        Map<String, Object> decoded = (Map<String, Object>) tokenAuth.getDetails();

        decoded.putAll( profile.getAppMetadata() );
        tokenAuth.setPrincipal( new Auth0UserDetails( decoded, getAuthorityStrategy() ) );
        tokenAuth.setDetails( decoded );
        
        return authentication;
    }
```

**Comment by geekbeast** [comment]
We have to manually used the `AuthenticationAPIClient` to manually retrieve the roles.  

You can check out what we're to retrieve the jwt token from Auth0 here:

https://github.com/kryptnostic/rhizome/blob/develop/src/test/java/digital/loom/rhizome/authentication/AuthenticationTest.java

**Comment by adrogon** [comment]
Hello @geekbeast,

How do you generate the token? Roles would appear if you set them in the scope.

For example, using `lock`, it looks like this:
`options: {
  auth: {
    params: {scope: 'openid email roles'}
  }
}`

The documentation is [here](https://auth0.com/docs/scopes).

Then make sure your `auth0.authorityStrategy` is set to `ROLES` and the authorities should be set in the `Auth0UserDetails` Principal.

Regards.

**Comment by geekbeast** [comment]
Thanks! That simplifies things quite a bit :)

I think it would still be helpful to have a link to that article from the Java documentation, in particular the spring documentation.

Without knowing that I should be searching for "scope" it's hard to glue together the write pieces to use the Auth0 jwt tokens to pass context between spring microservices.

**Comment by arcseldon** [comment]
@geekbeast - thank you for this feedback. The sample readme does detail all this [here](https://github.com/auth0-samples/auth0-spring-security-api-sample#test-the-api) but we shall ensure the official docs page gets updated [here](https://auth0.com/docs/quickstart/backend/java-spring-security) too. Pleased your issue is sorted out - shall leave this issue open until docs update completed.

**Comment by mpaktiti** [comment]
Thanks guys, the documentation has been updated 👍

**Comment by arcseldon** [comment]
@mpaktiti - Fantastic, thank you v.much!
