### ISSUE TITLE
Roles seem to be glossed over

### ISSUE THREAD

**Issue by stratosmacker** [auth0/auth0-spring-security-api#16]
Sort of a continuation of the closed https://github.com/auth0/auth0-spring-security-api/issues/14
I don't mean to piggyback, but having a similar problem I will.

I read all of the documentation mentioned in the bug (and more), but when requesting the following
`options: {
  auth: {
    params: {scope: 'openid email roles'}
  }
}`
roles are not retrieved. However when requesting 
`options: {
  auth: {
    params: {scope: 'openid email roles app_metadata'}
  }
}`
I get roles underneath the app_metadata object in the JWT response.

That however doesn't seem to work with auth0-spring-security AuthorityStrategy. Looking at ListAttributeStrategy.java , it looks like it only looks into the details Map one layer deep for the list of authorities. Some debugging seemed to confirm this (using the default ROLES strategy)

So if the JWT looks like
`
{
  "email": "josiecki@mesur.io",
  "app_metadata": {
    "roles": [
      "ROLE_ADMIN",
      "ROLE_USER"
    ],
`
This functionality seems not to work.

Thanks ahead of time, I just need some clarification. Furthermore is this a bug or user error, or something in between

**Comment by arcseldon** [comment]
@stratosmacker - thanks for raising this issue. Have put in a request with our docs team to clarify today's behaviour. Trying with `"scope":"openid email roles xyz app_metadata"` I see custom attributes `xyz` and `roles` both as top level claims and inside `app_metadata`. Can you confirm you also see same behaviour. Here i just set up a simple rule to add both attributes as follows:

```
function (user, context, callback) {
  user.app_metadata = user.app_metadata || {};
  var addRolesToUser = function(user, cb) {
      cb(null, ['ROLE_ADMIN', 'ROLE_USER']);
  };
  addRolesToUser(user, function(err, roles) {
    if (err) {
      callback(err);
    } else {
      user.app_metadata.roles = roles;
      user.app_metadata.xyz = 'xyz';
      auth0.users.updateAppMetadata(user.user_id, user.app_metadata)
        .then(function(){
          callback(null, user, context);
        })
        .catch(function(err){
          callback(err);
        });
    }
  });
}
```

**Comment by stratosmacker** [comment]
Yes I think we are on the same page. I am actually using a rule quite like that to set Roles (I think that's a wiki example right?).
Adding the xyz assignment into the rule I get the expected result:
`"app_metadata": {
        "roles": [
            "ROLE_ADMIN",
            "ROLE_USER"
        ],
        "admin_verified": true,
        "xyz": "xyz"
    },
`

So if the Java library is making a Top level claim for the Roles of a user, this will break it correct?

For fun I also set
`
user.roles = roles;
`
in the rule, but that doesn't seem to stick in the user object... :)

**Comment by arcseldon** [comment]
@stratosmacker - RE. your question, no it should not break it. The behaviour i am seeing is  that the custom attributes xyz and roles both as **top level claims** and **inside app_metadata**.   In other words, you can retrieve the same information from either the base of the JWT Token or by inspecting inside the app_metadata property itself.

**Comment by stratosmacker** [comment]
So making a JWT with 
`
options: { auth: { params: {scope: 'openid email roles'} } }
`
Should give the roles at the top level of the Object?

I get something more like
`
{
  "email": "email@email.com",
  "email_verified": true,
  "iss": "https://stratosmacker.auth0.com/",
  "sub": "auth0|1234567890",
  "aud": "16781612679812679812",
  "exp": 1479773054,
  "iat": 1479737054
}
`

**Comment by arcseldon** [comment]
Hi, no problem. Nope, what I am saying is add your `roles` attributes to `app_metadata` in your Rule. Then, call it with `{ auth: { params: {scope: 'openid email roles app_metadata'} } }` and you will get `roles` both at the base of the claims and inside the `app_metadata` attribute.

Am following up with the engineering and docs team to ensure this behaviour is both expected and consistent (and we are not seeing some regression issue) - but it is the configuration that currently works. Please confirm back here that this works for you.

**Comment by stratosmacker** [comment]
Hmm. Unfortunately, that doesn't seem to be how the JWT is coming back. Using 
`
{ auth: { params: {scope: 'openid email roles app_metadata'} } }
`
I get

`
{
  "email": "email@email.com",
  "email_verified": true,
  "app_metadata": {
    "roles": [
      "ROLE_ADMIN",
      "ROLE_USER"
    ],
    "admin_verified": true,
    "xyz": "xyz"
  },
  "iss": "https://stratosmacker.auth0.com/",
  "sub": "auth0|1234567890",
  "aud": "randomstring",
  "exp": 1479773740,
  "iat": 1479737740
}
`

**Comment by arcseldon** [comment]
As the saying goes, "well it works for me" ;)

Please can you give me the actual Auth0 tenant name you are using (i could not find `stratosmacker`) - i will check your account. Also, please confirm you are using the exact same RULE I posted earlier.

Finally, please (create a DB connection and add a new user from Users section of dashboard if not already exists) use the CURL command below, putting in your own details - then check what the JWT token looks like using [JWT IO](http://jwt.io).

```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
  "client_id":"YOUR CLIENT ID",
  "username":"YOUR EMAIL",
  "password":"YOUR PASSWORD",
  "connection":"YOUR DB CONNECTION NAME",
  "grant_type":"password",
  "scope":"openid email roles xyz app_metadata",
  "device":""
}' "https://YOUR TENANT NAME.auth0.com/oauth/ro"
```

**Comment by stratosmacker** [comment]
Sure thing. If you don't mind I'll pm you the details.

**Comment by stratosmacker** [comment]
sent to your @gmail

**Comment by arcseldon** [comment]
@stratosmacker - Thanks for email. Am based in Japan, hence the late reply.  Have sent you email response with explanation for this. Essentially, you have another conflicting Rule which is altering the default behaviour for scopes that I outlined above - full details in email.
