### ISSUE TITLE
CORS Filter - add "PATCH" method to the "Allow" header

### ISSUE THREAD

**Issue by danieldonev** [auth0/auth0-spring-security-api#17]
It seems that for some reason the CORS filter does not include "PATCH" as allowed methods Is there a reason for that, because i want to use the "PATCH" method.

**Comment by chenkie** [comment]
@arcseldon can you take a look?

**Comment by danieldonev** [comment]
Any feedback ?

**Comment by arcseldon** [comment]
@danieldonev - apologies for delays in responding to this issue. Taking a look now - hopefully you were able to define your own CORSFilter (based on the library's) and override with your own AppConfig in the interim?

**Comment by arcseldon** [comment]
Have added `PATCH` to the default CORSFilter configuration for this library. Note, the library is designed only to offer sensible defaults, and makes it easy for the user of the library to override with the specific Filter / Settings they require for their own API app(s). However, in this case, PATCH is certainly a reasonable default to add. 

Will be available in next minor release of this library once published.

**Comment by arcseldon** [comment]
@danieldonev - update published to maven central. Please retest and update here if poss. to confirm everything now works for you.

**Comment by danieldonev** [comment]
Yes the issue is resolved. BUT please change the version in documentation from 0.3.2 to 0.3.3. Thank you for the help.
