### ISSUE TITLE
Feature: multi-tennant awareness planned?

### ISSUE THREAD

**Issue by bastman** [auth0/auth0-spring-security-api#18]
Is there a feature planned to support multiple auth0 tennants within a spring-boot application?

And idea could be to let the backend-developer provide a whitelist of tennants being accepted by spring-security.

**Comment by lbalmaceda** [comment]
This is not something we plan, but feel free to leave your feature requests or suggestions right here so they can be reviewed by the product team https://auth0.com/feedback
