### ISSUE TITLE
JWT verification without audience

### ISSUE THREAD

**Issue by sicrossley** [auth0/auth0-spring-security-api#18]
I have an API that is used by multiple clients, and I want to be able to add new clients as needed without amending deployed code.

The `JwtWebSecurityConfigurer` allows me to supply my own `AuthenticationProvider` that doesn't include a `withAudience` on `JWTVerifier`, but I still have to specify an audience to the static factory methods `forHS256` and `forRS256`. I provide null, and it works fine, but it's just a bit untidy!

**Comment by hzalaz** [comment]
@sicrossley the audience is not the id of the clients but the id of the API, and is the way to tell if the token is meant for your API or another one. So you don't need to amend your deployed code on each new client.

**Comment by sicrossley** [comment]
@hzalaz You're correct if I use the OAuth2 client credentials flow from a serverside app, when I obtain a JWT from https://auth0.com/docs/api/authentication#!#post--oauth-token  The clientId is the subject, and the id of the API is the audience.

We're also connecting clients from mobile and single page apps to the same API. These JWTs contain the authenticated user id as the subject, and the audience is the client id. We create the JWTs using the js library (auth0-lock), I think they're the same as https://auth0.com/docs/api/authentication#!#post--oauth-ro 

Is there another way that the JWTs are intended to be used?
