### ISSUE TITLE
Cors and X-XSRF-TOKEN

### ISSUE THREAD

**Issue by uetanabaro** [auth0/auth0-spring-security-api#21]
Hello,

I got some problems with cross site and Auth0CORSFilter.java. I think i missing keyword "X-XSRF-TOKEN" in Access-Control-Allow-Headers and i got this error in angular2 console:

"Request header field X-XSRF-TOKEN is not allowed by Access-Control-Allow-Headers in preflight response."

**Comment by arcseldon** [comment]
@uetanabaro - not clear why you are sending that header to the API. That is an Angular XSRF feature for user sessions whereby you wish to associate a cookie with the request. This API is stateless and has no notion of session handling. Make sense?

**Comment by uetanabaro** [comment]
Yes you right, but when i do cross-site with angular2 it tests cross site with PARAMS method and expect X-XSRF-TOKEN in allowed content. I cant disable this feature in angular2.

**Comment by nikolassoares** [comment]
@uetanabaro How did you solve the problem, X-XSRF-TOKEN ?
