### ISSUE TITLE
Feature request : provide tooling/documentation for testing secure controllers using @WebMvcTest

### ISSUE THREAD

**Issue by mickaeltr** [auth0/auth0-spring-security-api#24]
So far, I have not been able to test the security of my Spring controllers using [@WebMvcTest](https://spring.io/guides/gs/testing-web/). I ended up disabling the security:
```java
@WebMvcTest(controllers = MyController.class, secure = false)
```
(by the way, [secure](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/web/servlet/WebMvcTest.html#secure--) is now deprecated, I am not sure how to replace it yet)

**I would like Auth0 to provide tooling or documentation for testing secure controllers using `@WebMvcTest`.**

### Documentation

This feature has been asked already on the Auth0 community forum: https://community.auth0.com/t/testing-a-secure-springboot-controller-using-webmvctest/9182

Okta provides documentation for the same use case: https://developer.okta.com/blog/2019/03/28/test-java-spring-boot-junit5

Here is a Spring add-on that could be helpful: https://github.com/ch4mpy/spring-addons/tree/master/spring-security-test-oauth2-addons

### Environment

I am using:
- Spring Boot 2.1.4
- Spring Security 5.1.5
- Auth0 Spring Security 1.2.1

Thanks :)

**Comment by jimmyjames** [comment]
Hi @mickaeltr - If you haven't yet, please take a moment to request any documentation or product improvements at [https://auth0.com/feedback](https://auth0.com/feedback). 

I did take a quick pass at this using Spring Boot 2.1.4 and Auth0 Spring Security 1.2.1. Using `WebMvcTest` in combination with `@WithMockUser` it should be possible to test secured APIs:

```
@AutoConfigureMockMvc
@ContextConfiguration(classes = {APIController.class })
@WebMvcTest
class APIControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @WithMockUser(username="user123")
    @Test
    public void testPrivate() throws Exception {
        MvcResult result = mockMvc.perform(MockMvcRequestBuilders.get("/api/private")
                .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andReturn();

        String resp = result.getResponse().getContentAsString();
        System.out.println("PRIVATE RESULT: " + resp);

        // compare expected result with actual result
    }

    @Test
    public void testPrivateWithNoUserThrowsUnauthorized() throws Exception {
        MvcResult result = mockMvc.perform(MockMvcRequestBuilders.get("/api/private")
                .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isUnauthorized())
                .andReturn();

        String resp = result.getResponse().getContentAsString();
        System.out.println("PRIVATE RESULT: " + resp);

        // compare expected result with actual result
    }
}
```

In addition to the resources you listed, Baeldung also has some good info, including [this article on integration testing with Spring Security](https://www.baeldung.com/spring-security-integration-tests).

Hope that helps, and don't forget to submit feedback for documentation updates.

**Comment by mickaeltr** [comment]
Hi @jimmyjames,
Thanks for the feedback.
I don't know yet why but `@WithMockUser` only works on GET requests! On my application, other methods return 403.
Could you please provide examples with other verbs?
Cheers

**Comment by mickaeltr** [comment]
My bad… I just figured out that tests on unsafe HTTP methods were failing not because of Auth0 but because of the CSRF.

Adding `.with(SecurityMockMvcRequestPostProcessors.csrf())` to the RequestBuilder fixes it.
