### ISSUE TITLE
Why are the `iss` and `aud` claims non-optional for HS-256?

### ISSUE THREAD

**Issue by sappenin** [auth0/auth0-spring-security-api#25]
### Question Description
When verifying tokens signed using `HS_256`, [`JwtAuthenticationProvider`](https://github.com/auth0/auth0-spring-security-api/blob/master/lib/src/main/java/com/auth0/spring/security/api/JwtAuthenticationProvider.java#L110) requires the presence of both the `iss` _and_ `aud` claims. There is no constructor that allows instantiation without them, and setting them to `null` or `""` will fail inside of [`JWTVerifier`](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L484) (that class is located  in https://github.com/auth0/java-jwt).

Is there any particular reason why it is not possible to omit these claims while using `JwtAuthenticationProvider`?

## Additional Context
RFC-7519 is pretty clear to say that [both of these claims are optional](https://tools.ietf.org/html/rfc7519#section-4.1.1). I can see why these claims would be useful for RS-256 use-cases, or for Auth0-generated tokens (i.e., 3rd-party token generators/verifiers), but in my case I have an application-specific use-case of HS-256, and adding the `aud` and `iss` claims doesn't seem to add very much (if any) value.

My use-case is a peer-to-peer auth scenario using a shared secret. There is only over one type of "endpoint" (so the `aud` claim doesn't add any value) and the tokens are only ever valid between two peers (so the `iss` claim seems to be mostly redundant).

Thinking through some attack vectors in scenarios where these two claims are present/absent:

* If an attacker were to compromise the underlying shared-secret used to generated the HS_256 JWTs, then the attacker could simply forge the `iss` and `aud` claims.
* If an attacker were to compromise a JWT in-transit, it would only work between two peers anyway, though I suppose including the `aud` claim would limit the attacker to only being able to make malicious calls on only _one_ of the peers, which seems somewhat useful.

Aside from what I've mentioned, is there some other security reason the library doesn't allow these claims to be absent?

Thanks!

### Prerequisites

- [X] I have checked the documentation for this library in the README.
- [X] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [X] I have checked for related or duplicate [Issues](https://github.com/auth0/java-jwt/issues) and [PRs](https://github.com/auth0/java-jwt/pulls).
- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [X] I am reporting this to the correct repository (note this library is used by many libraries, such as [auth0-java](https://github.com/auth0/auth0-java)).

### Environment

Please provide the following:

- Version of this library used: `master` branch.
- Version of Java framework used: `JDK8`
- Additional libraries that might be affecting your instance: `n/a`

**Comment by lbalmaceda** [comment]
@sappenin first things first. This is a library dedicated to the **Auth0 specifics** authentication and (some) authorization flows. The `iss` claim is added on all server issued tokens, as far as I remember. The `aud` one defines which APIs will be able to consume the token. In the case of this api/backend library, that's a necessary check, right? since your API would like first to check that the token received was issued to be consumed by them. What do you win removing that check, is that to shorten the token length?


> If an attacker were to compromise the underlying shared-secret....

Say no more. In that scenario, everything is compromised. The secret is secret and shouldn't be shared or used in public/unsecure clients at all. I strongly encourage you to [move](https://github.com/auth0/auth0-spring-security-api#usage) to `RS256` (Auth0 does support this) and make use of the public key certificate to validate those signatures as explained [here](https://github.com/auth0/auth0-spring-security-api/blob/48d860fa0360aaefa21ce639737bd60898e70afc/lib/src/main/java/com/auth0/spring/security/api/JwtWebSecurityConfigurer.java#L27).

Again, this library is focused on the Auth0 product. Cheers

**Comment by sappenin** [comment]
@lbalmaceda Thanks so much for your response!

> This is a library dedicated to the Auth0 specifics authentication and (some) authorization flows

That makes sense, my apologies for the oversight. I originally posted this into [java-jwt](https://github.com/auth0/java-jwt) thinking the problem was in that library, but once I realized the actual class that was preventing me (JwtAuthenticationProvider) lived in here, I just re-posted without looking. Sorry about that.

> What do you win removing that check, is that to shorten the token length?

Not really. Instead, the motivation is to reduce the amount of information two peers need to exchange in order to use tokens together. Without these extra claims, two peers can basically just exchange a shared secret and immediately start making requests with the other.

> In that scenario, everything is compromised. The secret is secret and shouldn't be shared or used in public/unsecure clients at all.

Agree with your sentiment around the secret being compromised. The primary thrust of my question is instead around token compromise (as opposed to shared-secret compromise), though my question doesn't do a great job of emphasizing that. Incidentally, "token compromise" is possible with an RSA token as well, though I think adding these claims (in either scheme) helps reduce the attack surface.

In any event, I think the answer to my question is that these claims should be included if possible. I'll close this issue, but feel free to add more thoughts if you have them.
