### ISSUE TITLE
Seems the src folder has disappeared from the master branch

### ISSUE THREAD

**Issue by eepstein** [auth0/auth0-spring-security-api#26]
Looks like a good number of changes from the v0.x branch and closer integration with Spring via the WebSecurityConfigurerAdapter approach.  Good things.

BUT.... when looking here on github there's a gradle wrapper (an anti-pattern, by the way, despite what the folks at gradle.org advocate - just add a "wrapper" task to your build.gradle and let the user run: "gradle wrapper; ./gradlew foo" rather than put 3rd party jars into your repo.... pet peeve... anyway) other than a readme and some top level project config files there's no code in the repo!

**Comment by hzalaz** [comment]
The lib folder has the source
