### ISSUE TITLE
spring security dependencies should be compileonly

### ISSUE THREAD

**Issue by jeacott1** [auth0/auth0-spring-security-api#28]
if people ard using spring security they are going to already have the dependencies.included in their own build

**Comment by hzalaz** [comment]
The library jar does not include spring or any other dependencies (its not a fat jar) so when you add it via maven it will try to solve the correct spring version based in our lib and your app. Is there something else you are worried about?

**Comment by jeacott1** [comment]
yeah, the pom hauls in specific versions of a bunch of dependencies and requires them at runtime.
should be compileOnly

https://blog.gradle.org/introducing-compile-only-dependencies
