### ISSUE TITLE
No possibility to setup the 'leeway'

### ISSUE THREAD

**Issue by Igor-G** [auth0/auth0-spring-security-api#31]
There's no way to configure the 'leeway' for the JWTVerifier with the available JwtAuthenticationProvider.
I had to implement a custom AuthenticationProvider (basically a copy of the JwtAuthenticationProvider) with the possibility to setup the 'leeway' for the 'issuedAt' date (to cover the timing mismatch between the server generating the JWT and the server verifying in).

Please provide some API for setting the leeway for all possible dates.

**Comment by hzalaz** [comment]
Yes, we could add that. Also PRs are welcome!

**Comment by pacey** [comment]
I'd be happy to work on this. At the moment the `JwtAuthenticationProvider` has static methods with the `issuer` and `audience` strings as parameters. I could add the leeway as an extra one, but that feels a bit wrong. Do you have any suggestions for how you'd like the extra verification options provided?

**Comment by hzalaz** [comment]
Maybe a method in the configurer but I have no strong opinion now

**Comment by jspetrak** [comment]
I've just had the same need. Would suggest to create the `withJWTVerifyLeeway()` method in `JwtAuthenticationProvider`, store the parameter, pass it to in `providerForHS256` method IF not null. And would use the `forRS256(String audience, String issuer, AuthenticationProvider provider)` method of `JwtWebSecurityConfigurer`. 

@pacey Do you want to implement it? Otherwise I can contribute.

**Comment by jspetrak** [comment]
@hzalaz I have provided PR#40 as an idea how to do it.

**Comment by shorn** [comment]
Am using implementation from @jspetrak (changed to subclass original class) in the interim.  Works enough for me to get on with other things - please comment if anyone finds a major problem with it.

**Comment by Oduig** [comment]
Just stumbled upon this problem, because the browser clock was a second ahead of the server clock.

Since this is supposed to integrate with Spring, how about using a @Bean instead of a static function? That way we could easily supply our own JWTVerifier without having to change all the APIs.
