### ISSUE TITLE
Any chance for new release?

### ISSUE THREAD

**Issue by michalig** [auth0/auth0-spring-security-api#32]
Hi, is there any chance for new release with com.auth0:java-jwt:3.1.0? I see it's already in master. I'm trying to use application_metadata and with old version of java-jwt it seems impossible.

**Comment by brickyard** [comment]
+1

**Comment by lbalmaceda** [comment]
We will hold for java-jwt:3.2.0 to be released.

**Comment by jeacott1** [comment]
https://mvnrepository.com/artifact/com.auth0/java-jwt/3.2.0
