### ISSUE TITLE
Permissions support

### ISSUE THREAD

**Issue by skjolber** [auth0/auth0-spring-security-api#36]
Support [API permissions](https://auth0.com/docs/dashboard/guides/apis/add-permissions-apis).
 
### Description

We're getting tokens with `permissions` from Auth0.

Replace scopes with permissions, in [AuthenticationJsonWebToken.java](https://github.com/auth0/auth0-spring-security-api/blob/master/lib/src/main/java/com/auth0/spring/security/api/authentication/AuthenticationJsonWebToken.java#L41.).

```json
{
  "iss": "https://x.y.z.org/",
  "sub": "u.i",
  "aud": [
    "https://my.dev.env.org",
    "https://my-dev.x.auth0.com/userinfo"
  ],
  "iat": 1568211075,
  "exp": 1568114275,
  "azp": "o.p.q",
  "scope": "openid profile email",
  "permissions": [
    "stuff:configure",
    "sop:configure",
    "settings:configure",
    "turnover:view",
    "admin:configure"
  ]
}
```

We would like to use these in method-based security in Spring.

### Prerequisites

- [ ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-spring-security-api/issues) and [PRs](https://github.com/auth0/auth0-spring-security-api/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I am reporting this to the correct repository [Add links to other related].

### Environment

Latest master version.

### Reproduction
Authenticate user with single page application.

**Comment by jimmyjames** [comment]
Hi @skjolber,

I don't think we want to _replace_ creating `GrantedAuthority` from scopes with permissions, as scopes still are valid. But I agree we do need to evaluate support for allowing APIs to be secured using the `permissions` claim.

Spring 5 does this [by adding a prefix](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2resourceserver-authorization) to the the `GrantedAuthority`, e.g., `SCOPE_read:messages`, and allows for creating custom extractors to enable using different claims, etc. We could consider following a similar pattern (while not breaking existing implementations by requiring the `SCOPE_` prefix). I'm not yet sure how feasible it will be to enable custom Authority extractors here, but it's also something to consider.
