### ISSUE TITLE
Support for Curves

### ISSUE THREAD

**Issue by musiKk** [auth0/auth0-spring-security-api#38]
We are using JWT's with ES384 which unfortunately is not supported by the provided `JwtAuthenticationProvider`; it only supports RS384 and HS256. We basically had to copy the existing authentication provider and implement it ourselves. This works well enough but is a bit fiddly and disturbs the out-of-the-box experience. Is it planned that support for curves is added? Do you need help with that?

**Comment by lbalmaceda** [comment]
@musiKk this lib was made with [Auth0](https://auth0.com) in mind. When you create an Auth0 client you can ask the server to sign the access tokens either with HS256 (using the client secret) or with RS256 (using the private key). Support for ES is out of this SDK's scope.
Cheers.

**Comment by musiKk** [comment]
Got it, thanks for the reply!
