### ISSUE TITLE
JWTVerifier with varargs is ambiguous

### ISSUE THREAD

**Issue by tenjaa** [auth0/auth0-spring-security-api#39]
Hey,
we ran into an issue that is described in another project of your org.
https://github.com/auth0/java-jwt/issues/344

An backwards compatible fix would probably be to provide another constructor.
But I doubt that anyone should be passing null into the audience, as it is just not working as expected.
So changing the construcor param to varargs and then handling it could also be an option.

Tell me what you think and I am happy to provide a pull request.

**Comment by tenjaa** [comment]
I don't think that's resolved yet

**Comment by ssrm** [comment]
I also ran into same issue, I have kept a pull request on java-jwt project, have to see what will happen to that pr.

**Comment by jimmyjames** [comment]
I've verified that this issue is resolved. It was fixed in the `java-jwt` library by [this PR](https://github.com/auth0/java-jwt/pull/412). If you are using version `1.3.1` or later of this library and still seeing this issue, please reopen so we can investigate further. Thanks!
