### ISSUE TITLE
Spring Webflux Support

### ISSUE THREAD

**Issue by c0nscience** [auth0/auth0-spring-security-api#43]
### Describe the problem you'd like to have solved

The current version of the library does not support spring webflux. A reactive programming model is an interesting paradigm and a first party support from auth0 would be very beneficial to avoid broken custom implementations

### Describe the ideal solution

A simple configuration variant as shown in this commit: https://github.com/Tikinou/auth0-spring-security-api/commit/3ab508fd6154a4ca9488465a207923cf972166c9

## Alternatives and current work-arounds

Copy pasting over the code from the above mentioned commit and loosing therefore any upstream support.

### Additional context

- Link to the first draft implementation: https://github.com/Tikinou/auth0-spring-security-api/commit/3ab508fd6154a4ca9488465a207923cf972166c9

**Comment by jimmyjames** [comment]
:wave: Hi @c0nscience, thanks for the feedback!

I agree, the reactive features introduced in Spring 5 via WebFlux are awesome! Spring 5 / Spring Boot 2 also has added support for OIDC/OAuth2, for which we have a [Quickstart](https://auth0.com/docs/quickstart/backend/java-spring-security5/01-authorization) and an accompanying [sample app](https://github.com/auth0-samples/auth0-spring-security5-api-sample/tree/master) that demonstrates securing an API with Auth0, including both MVC and WebFlux configurations :smile:. I recommend checking those out for pretty easy authorization of APIs with Spring 5 and Auth0.

Let me know if that helps, thanks!

**Comment by c0nscience** [comment]
@jimmyjames sweet! Thank you very much this is a way better solution 👍 Just switched to it and it all works as it did before. So that means this library here is basically deprecated right?

**Comment by jimmyjames** [comment]
Hi @c0nscience , glad that you found that sample useful! 👍 

We are looking into what the future of this SDK should be. We could update it similar to the link you provided to support Spring 5, but we should understand what benefits that gives us versus providing guidance on configuring Spring Security for Auth0 without the need for this SDK (for those on Spring Boot 2 / Spring 5). And longer term, there's an opportunity to provide a Spring Boot Starter to even further reduce the amount of configuration and code needed (both for authorization and authentication).

I'm currently leaning towards an incremental approach that would:

- Clearly document this SDK is only supported for Spring Boot 1 / Spring Security 4, and refer to our Spring Security 5 Quickstart/sample for guidance targeting those platforms.
- Update our Quickstarts/samples to provide guidance on how to add Auth0 for authentication/login to Spring Boot 2 / Spring 5 apps through the OOTB configuration.
- Look at providing a Spring Boot Starter in the future to make Auth0 integration even easier going forward, along with providing a spot to provide additional Auth0-specific features easily.

That said, I'd love to hear your or others thoughts around that approach. Thanks!

**Comment by c0nscience** [comment]
@jimmyjames yeah that sounds good. Having a starter in the end would be very nice.

**Comment by jimmyjames** [comment]
I've updated the README with clearer Spring version support, along with a link to that Quickstart/sample for Spring 5/Spring Boot 2. Will continue to look at providing a starter at some point in the future, as I 100% agree it's the most ideal solution for Spring going forward 💯
