### ISSUE TITLE
Question: How to save user locally in database on authentication?

### ISSUE THREAD

**Issue by peavers** [auth0/auth0-spring-security-api#44]
I can't seem to find any guidance on how to do this using Auth0. Looking at the code in the library I shouldn't have to manually do much in order to get things working but not having any luck. 

How should I go about creating/updating a user in a database whenever they authenticate? 

I attempted to extend `JwtAuthenticationProvider` however didn't have much luck there. 

Is there any "real world" applications implementing this library where examples could be provided?

**Comment by lbalmaceda** [comment]
Spring context is supposed to store the `Authentication` instance for you. Once you obtain it, you should be able to get the JWT contents as that's what the `JwtAuthenticationProvider` [returns on authentication](https://github.com/auth0/auth0-spring-security-api/blob/master/lib/src/main/java/com/auth0/spring/security/api/JwtAuthenticationProvider.java#L55). I don't remember quite well the classes right now, but you should be doing something like this:

```java
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
if (authentication instanceof JwtAuthentication) {
    String token = authentication.getToken();
    // decode the token and obtain the claims.
    // because token should already been verified, you can just decode it.
}
```

**Comment by peavers** [comment]
Awesome cheers for that, that makes total sense. Just one question, where abouts in the flow would you call something like that? In my security config after the token is verified?

**Comment by lbalmaceda** [comment]
Ah! sorry I thought you wanted to obtain the token claims to extract user information later in your api. 🤦‍♂️ . If you need to hook into a successful authentication, either implement your own authentication chain [like this library does](https://github.com/auth0/auth0-spring-security-api/blob/master/lib/src/main/java/com/auth0/spring/security/api/JwtWebSecurityConfigurer.java#L100) and emit that "success" event somewhere after verifying the token or check the `ApplicationListener` class from Spring Security that [could help](https://stackoverflow.com/a/14043376) listening to events of this nature. I don't have another answer as I haven't required this a lot. AFAIK by default, upon failed authentication Spring will return 401 and stop the chain right there.

**Comment by peavers** [comment]
Hmm sorry for the confusion... I think you were right the first time, I'm just not explaining myself clearly, and I'm pretty fresh to Spring in general. 

All I'm trying to do is save a user into MongoDB when they log in so I can save extra custom information about them. At the moment I have people authenticating correctly with Auth0 and getting a valid JWT; I'm just not sure how to save those people into Mongo. 

Would it look something like this, or am I completely off the ball? 

    @Override
    protected void configure(HttpSecurity httpSecurity) throws Exception {
        httpSecurity.csrf().disable();
        httpSecurity.cors();
        httpSecurity.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.NEVER);

        JwtWebSecurityConfigurer
                .forRS256(audience, issuer)
                .configure(httpSecurity)
                .csrf().disable()
                .authorizeRequests()
                .anyRequest().authenticated();

        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication instanceof JwtAuthentication) {
            String token = ((JwtAuthentication) authentication).getToken();
            
            
            // Check if the user exists and update, or create new - obviously using
            // real values from the decoded token
            User user = new User();
            user.setUsername("Steve");
            userRepository.save(user);
        }
    }

**Comment by lbalmaceda** [comment]
No as the configure method is going to get called only once when the app is first run to configure the security chain, so at that time you won't have an authentication instance in the context holder. Also, the "authenticate this given token" step is going to get called for every request, that's how authenticators work, remember that this is stateless. I'd think twice if I really need to be writing to the db the same values on every request. I'm no expert in Spring either, I'd love to help you though 😞 I'd suggest you ask in the [Auth0 community](community.auth0.com) or in the [Spring forums](http://forum.spring.io/) maybe you have more luck.

**Comment by peavers** [comment]
You're correct, I think I'd just gone deep down the wrong rabbit hole and lost sight of what I was actually trying to achieve, cheers for the answers though they have pointed me in the correct direction :)
