### ISSUE TITLE
Published package missing dependencies

### ISSUE THREAD

**Issue by Jazzepi** [auth0/auth0-spring-security-api#44]
### Description
I started wtih version 1.0.0 which had these first-level published dependencies.
```
com.auth0:auth0-spring-security-api:1.0.0
com.auth0:java-jwt:3.3.0
com.auth0:jwks-rsa:0.3.0
com.fasterxml.jackson.core:jackson-databind:2.9.4
commons-codec:commons-codec:1.11
org.slf4j:slf4j-api:1.7.25
org.springframework.security:spring-security-config:4.2.4.RELEASE
org.springframework.security:spring-security-core:4.2.4.RELEASE
org.springframework.security:spring-security-web:4.2.4.RELEASE
```
I started version 1.3.0 has NO first-level published dependencies.
```
(none)
```
which broke the example of using the `JwkProviderBuilder`
```
                .authenticationProvider(
                        new JwtAuthenticationProvider(
                                new JwkProviderBuilder(<omitted>).build(), <omitted>, <ommitted>)
                )
```
You may want to include those dependencies, or make a note of where the class JwkProviderBuilder can be found.

**Comment by maxkramer** [comment]
Seems that this issue first appears in v1.2.0. Upgrading from 1.1.0 to 1.{2|3}.0 gives me the issue that when anything from the `org.springframework.security` package is missing

**Comment by jimmyjames** [comment]
Thanks for the report! You are correct, dependencies were changed from `compile` to `implementation`, so those dependencies are no longer exposed. We'll get a change in to surface those dependencies needed by this SDK. In the meantime, you can of course add the dependencies you need manually.

**Comment by Jazzepi** [comment]
No problem :)

**Comment by jimmyjames** [comment]
Hi @Jazzepi and @maxkramer I have a [PR](https://github.com/auth0/auth0-spring-security-api/pull/45) to address this. If you want to take a look and provide feedback, that would be appreciated, then we can get this released to fix this issue 👍
