### ISSUE TITLE
PreAuthenticatedAuthenticationJsonWebToken uses wrong class for logging

### ISSUE THREAD

**Issue by Xabin** [auth0/auth0-spring-security-api#55]
PreAuthenticatedAuthenticationJsonWebToken uses class JwtAuthenticationProvider for logging:
public class PreAuthenticatedAuthenticationJsonWebToken implements Authentication, JwtAuthentication {
    private static Logger logger = LoggerFactory.getLogger(JwtAuthenticationProvider.class);

I'm guessing this is a copy-paste error. It confused me during troubleshooting.

**Comment by lbalmaceda** [comment]
Thanks! TBH I don't know if that was intentional or not. But it makes sense to use the current class in the Logger. I'll add this to my backlog unless you want to submit a PR, of course.
