### ISSUE TITLE
Update to java-jwt 3.18.3 for jackson security vulnerability

### ISSUE THREAD

**Issue by rhanton** [auth0/auth0-spring-security-api#61]
### Describe the problem

Like other spring MVC library, this lib should have dependencies brought up to date, particularly https://github.com/auth0/java-jwt/releases/tag/3.18.3 should get pulled in.

### What was the expected behavior?

Should not have jackson known vulnerability.

### Reproduction

Unknown

### Environment

N/A

**Comment by poovamraj** [comment]
Hi @rhanton Thanks a lot for bumping this up. We currently have PR #62  that is fixing this. The new version will be released soon so closing this issue. Please feel free to open it back if you have more queries.
