### ISSUE TITLE
Doc update: `WebSecurityConfigurerAdapter` is deprecated

### ISSUE THREAD

**Issue by AlexanderNZ** [auth0/auth0-spring-security-api#70]
Auth0's documentation published within this repo, and on quickstarts for Spring related projects across Auth0 refer frequently to WebSecurityConfigurerAdapter.

This method of configuration is deprecated. The docs in `WebSecurityConfigurerAdapter.java` suggests:

> Use a org.springframework.security.web.SecurityFilterChain Bean to configure HttpSecurity or a WebSecurityCustomizer Bean to configure WebSecurity

Please consider updating these docs so that they don't advocate for deprecated security config methods.

PS - recommend an issue type for doc requests - this obviously isn't a feature request or a bug and I didn't have many better options to report this :)

**Comment by poovamraj** [comment]
Hey @AlexanderNZ thanks a lot for this. We are looking into this and planning to fix this asap. Will keep you in the loop about it 👍

**Comment by poovamraj** [comment]
Hi @AlexanderNZ, The docs are updated to use the latest SecurityFilterChain. Thanks for reporting this, we are closing this now. Please feel free to reopen it if you have any more questions
