### ISSUE TITLE
Using JwtWebSecurityConfigurer with multiple audiences doesn't seem to work

### ISSUE THREAD

**Issue by nikolagencic** [auth0/auth0-spring-security-api#83]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spring-security-api#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0/auth0-spring-security-api/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spring-security-api/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, I am trying to set up two different audiences for 2 different API root paths in my Spring application.

The first class looks like this:

```
@Configuration
@Order(2)
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class AdminSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {

		JwtWebSecurityConfigurer
				.forRS256(TOKEN_AUDIENCE_1, TOKEN_ISSUER_1)
				.configure(http.antMatcher(PATH1))
```

And the second like this:

```
@Configuration
@Order(4)
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {

		JwtWebSecurityConfigurer
				.forRS256(TOKEN_AUDIENCE_2, TOKEN_ISSUER_2)
				.configure(http.antMatcher(PATH2))
```

But the problem is that the PATH2 is excluded from authentication - the PATH1 works properly and checks the authentication against the first principal, but the second set of end-points that start with PATH2 ignore authentication, and can be called without it?

### Reproduction

Described in the "Description" section.

### auth0-spring-security-api version

1.0.0-rc.3

### Java version

8

**Comment by jimmyjames** [comment]
👋 hi @nikolagencic - Auth0 does not support multiple audiences. Instead, you can [use scopes to represent multiple APIs 6.4k](https://auth0.com/docs/get-started/apis/set-logical-api).
